# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Sentence.destroy_all

raw_text = [
  "We have to create culture, don't watch TV, don't read magazines, don't even listen to NPR. Create your own roadshow. The nexus of space and time where you are now is the most immediate sector of your universe, and if you're worrying about Michael Jackson or Bill Clinton or somebody else, then you are disempowered, you're giving it all away to icons, icons which are maintained by an electronic media so that you want to dress like X or have lips like Y. This is shit-brained, this kind of thinking. That is all cultural diversion, and what is real is you and your friends and your associations, your highs, your orgasms, your hopes, your plans, your fears. And we are told 'no', we're unimportant, we're peripheral. 'Get a degree, get a job, get a this, get a that'. And then you're a player, you don't want to even play in that game. You want to reclaim your mind and get it out of the hands of the cultural engineers who want to turn you into a half-baked moron consuming all this trash that's being manufactured out of the bones of a dying world.",
  "Chaos is what we've lost touch with. This is why it is given a bad name. It is feared by the dominant archetype of our world, which is Ego, which clenches because its existence is defined in terms of control.",
  "Nature loves courage. You make the commitment and nature will respond to that commitment by removing impossible obstacles. Dream the impossible dream and the world will not grind you under, it will lift you up. This is the trick. This is what all these teachers and philosophers who really counted, who really touched the alchemical gold, this is what they understood. This is the shamanic dance in the waterfall. This is how magic is done. By hurling yourself into the abyss and discovering it's a feather bed.",
  "If the words 'life, liberty, and the pursuit of happiness' don't include the right to experiment with your own consciousness, then the Declaration of Independence isn't worth the hemp it was written on.",
  "Psychedelics are illegal not because a loving government is concerned that you may jump out of a third story window. Psychedelics are illegal because they dissolve opinion structures and culturally laid down models of behaviour and information processing. They open you up to the possibility that everything you know is wrong.",
  "The syntactical nature of reality, the real secret of magic, is that the world is made of words. And if you know the words that the world is made of, you can make of it whatever you wish.",
  "You are an explorer, and you represent our species, and the greatest good you can do is to bring back a new idea, because our world is endangered by the absence of good ideas. Our world is in crisis because of the absence of consciousness.",
  "You have to take seriously the notion that understanding the universe is your responsibility, because the only understanding of the universe that will be useful to you is your own understanding.",
  "You are a divine being. You matter, you count. You come from realms of unimaginable power and light, and you will return to those realms.",
  "Television is by nature the dominator drug par excellence. Control of content, uniformity of content, repeatability of content make it inevitably a tool of coersion, brainwashing, and manipulation.",
  "The creative act is a letting down of the net of human imagination into the ocean of chaos on which we are suspended, and the attempt to bring out of it ideas. It is the night sea journey, the lone fisherman on a tropical sea with his nets, and you let these nets down - sometimes, something tears through them that leaves them in shreds and you just row for shore, and put your head under your bed and pray. At other times what slips through are the minutiae, the minnows of this ichthyological metaphor of idea chasing. But, sometimes, you can actually bring home something that is food, food for the human community that we can sustain ourselves on and go forward.",
  "Ego is a structure that is erected by a neurotic individual who is a member of a neurotic culture against the facts of the matter. And culture, which we put on like an overcoat, is the collectivized consensus about what sort of neurotic behaviors are acceptable.",
  "We have been to the moon, we have charted the depths of the ocean and the heart of the atom, but we have a fear of looking inward to ourselves because we sense that is where all the contradictions flow together.",
  "My technique is don’t believe anything. If you believe in something, you are automatically precluded from believing its opposite.",
  "Nobody is smarter than you are. And what if they are? What good is their understanding doing you?",
  "The apocalypse is not something which is coming. The apocalypse has arrived in major portions of the planet and it’s only because we live within a bubble of incredible privilege and social insulation that we still have the luxury of anticipating the apocalypse.",
  "Nature is not our enemy, to be raped and conquered. Nature is ourselves, to be cherished and explored.",
  "Life lived in the absence of the psychedelic experience that primordial shamanism is based on is life trivialized, life denied, life enslaved to the ego.",
  "I’ll try to be around and about. But if I’m not, then you know that I’m behind your eyelids, and I’ll meet you there",
  "The imagination is the goal of history. I see culture as an effort to literally realize our collective dreams.",
  "It's clearly a crisis of two things: of consciousness and conditioning. We have the technological power, the engineering skills to save our planet, to cure disease, to feed the hungry, to end war; But we lack the intellectual vision, the ability to change our minds. We must decondition ourselves from 10,000 years of bad behavior. And, it's not easy.",
  "We can begin the restructuring of thought by declaring legitimate what we have denied for so long. Lets us declare Nature to be legitimate. The notion of illegal plants is obnoxious and ridiculous in the first place.",
  "Right here and now, one quanta away, there is raging a universe of active intelligence that is transhuman, hyperdimensional, and extremely alien... What is driving religious feeling today is a wish for contact with this other universe.",
  "Even as the nineteenth century had to come to grips with the notion of human descent from apes, we must now come to terms with the fact that those apes were stoned apes.",
  "Alcohol is used by millions of people, both men and women, and I will make no friends by taking the position that alcohol culture is not politically correct. Yet how can we explain the legal toleration for alcohol, the most destructive of all intoxicants, and the almost frenzied efforts to repress nearly all other drugs? Could it not be that we are willing to pay the terrible toll that alcohol extracts because it is allowing us to continue the repressive dominator style that keeps us all infantile and irresponsible participants in a dominator world characterized by the marketing of ungratified sexual fantasy?",
  "The shaman is not merely a sick man, or a madman; he is a sick man who has healed himself.",
  "My voice speaking is a monkey's mouth making little mouth noises that are carrying agree-upon meaning, and it is meaning that matters. Without the meaning one has only little mouth noises.",
  "It is the imagination that argues for the Divine Spark within human beings. It is literally a decent of the World's Soul into all of us.",
  "We tend to disempower ourselves. We tend to believe that we don’t matter. And in the act of taking that idea to ourselves we give everything away to somebody else, to something else.",
  "The purpose of life is to familiarize oneself with this after-death body so that the act of dying will not create confusion in the psyche.",
  "It is not easy to measure the ocean, but we can be measured by it, confront it, and be in it.",
  "Not to know one's true identity is to be a mad, disensouled thing — a golem. And, indeed, this image, sick-eningly Orwellian, applies to the mass of human beings now living in the high-tech industrial democracies. Their authenticity lies in their ability to obey and follow mass style changes that are conveyed through the media. Immersed in junk food, trash media, and cryp-tofascist politics, they are condemned to toxic lives of low awareness. Sedated by the prescripted daily television fix, they are a living dead, lost to all but the act of consuming.",
  "Ecstasy is a complex emotion containing elements of joy, fear, terror, triumph, surrender, and empathy. What has replaced our prehistoric understanding of this complex of ecstasy now is the word comfort, a tremendously bloodless notion. Drugs are not comfortable, and anyone who thinks they are comfortable or even escapist should not toy with drugs unless they’re willing to get their noses rubbed in their own stuff.",
  "Nothing comes unannounced, but many can miss the announcement. So it's very important to actually listen to your own intuition rather than driving through it.",
  "We are told 'no', we're unimportant, we're peripheral. 'Get a degree, get a job, get a this, get a that.' And then you're a player, you don't want to even play in that game. You want to reclaim your mind and get it out of the hands of the cultural engineers who want to turn you into a half-baked moron consuming all this trash that's being manufactured out of the bones of a dying world.",
  "A hallucination is a species of reality, as capable of teaching you as a videotape about Kilimanjaro or anything else that falls through your life.",
  "The ufo is nothing more than an assertion of herself by the Goddess into history, saying to science and paternalistically governed and driven organizations: You have gone far enough. We are going to turn the world upside down. Your science is going to be shown up for what it is, nothing more than a pleasant metaphor usefully extrapolated into the production of toys for healthy children. That's what science is good for. It is not some meta-theory at whose feet every point of view from astrology to acupressure to channeling need be laid to have the hand of science announce thumbs up or thumbs down.",
  "Reality is, you know, the tip of an iceberg of irrationality that we've managed to drag ourselves up onto for a few panting moments before we slip back into the sea of the unreal.",
  "I often like to think that our map of the world is wrong, that where we have centered physics, we should actually place literature as the central metaphor that we want to work out from. Because I think literature occupies the same relationship to life that life occupies to death. A book is life with one dimension pulled out of it. And life is something that lacks a dimension which death will give it. I imagine death to be a kind of release into the imagination in the sense that for characters in a book, what we experience is an unimaginable dimension of freedom.",
  "There’s light at the end of the tunnel. The problem is that tunnel is in the back of your mind. And if you don’t go to the back side of your mind you will never see the light at the end of the tunnel. And once you see it, then the task becomes to empower it in yourself and other people. Spread it as a reality. God did not retire to the seventh heaven, God is some kind of lost continent IN the human mind.",
  "Our self discoveries make us each a microcosm of the larger pattern of history. The inertia of introspection leads toward recollection, for only through memory is the past recaptured and understood. In the fact of experiencing and making the present, we are all actors.",
  "The artist’s task is to save the soul of mankind; and anything less is a dithering while Rome burns. Because of the artists, who are self-selected, for being able to journey into the Other, if the artists cannot find the way, then the way cannot be found.",
  "But technology is the real skin of our species. Humanity, correctly seen in the context of the last five hundred years, is an extruder of technological material. We take in matter that has a low degree of organization; we put it through mental filters, and we extrude jewelry, gospels, space shuttles. This is what we do. We are like coral animals embedded in a technological reef of extruded psychic objects. All our tool making implies our belief in an ultimate tool. That tool is the flying saucer, or the soul, exteriorized in three-dimensional space.",
  "What civilization is, is 6 billion people trying to make themselves happy by standing on each other's shoulders and kicking each other's teeth in. It's not a pleasant situation.",
  "This is why the shaman is the remote ancestor of the poet and artist. Our need to feel part of the world seems to demand that we express ourselves through creative activity. The ultimate wellsprings of this creativity are hidden in the mystery of language. Shamanic ecstasy is an act of surrender that authenticates both the individual self and that which is surrendered to, the mystery of being. Because our maps of reality are determined by our present circumstances, we tend to lose awareness of the larger patterns of time and space. Only by gaining access to the Transcendent Other can those patterns of time and space and our role in them be glimpsed.",
  "Part of what psychedelics do is they decondition you from cultural values. This is what makes it such a political hot potato. Since all culture is a kind of con game, the most dangerous candy you can hand out is one which causes people to start questioning the rules of the game.",
  "It's clearly a crisis of two things: of consciousness and conditioning. These are the two things that the psychedelics attack. We have the technological power, the engineering skills to save our planet, to cure disease, to feed the hungry, to end war; But we lack the intellectual vision, the ability to change our minds. We must decondition ourselves from 10,000 years of bad behavior. And, it's not easy.",
  "No culture on earth is as heavily narcotized as the industrial West in terms of being inured to the consequences of maladaptive behavior. We pursue a business-as-usual attitude in a surreal atmosphere of mounting crises and irreconcilable contradictions.",
  "Our culture, self-toxified by the poisonous by-products of technology and egocentric ideology, is the unhappy inheritor of the dominator attitude that alteration of consciousness by the use of plants or substances is somehow wrong, onanistic, and perversely antisocial. I will argue that suppression of shamanic gnosis, with its reliance and insistence on ecstatic dissolution of the ego, has robbed us of life’s meaning and made us enemies of the planet, of ourselves, and our grandchildren. We are killing the planet in order to keep intact the wrongheaded assumptions of the ego-dominator cultural style.",
  "I guess I should say a little bit about my method - I really am a fence sitter. I *loathe* Science and am always keen to attack it in most situations, though not here, because I love Reason and I'm perfectly aware of the difference. I also know what a concept means like Rules of Evidence. I'm not sure that's a concept as widely circulated in these circles as it needs to be - in other words, how *do* you tell shit from shinola? That's very critical. I think reason can only take us a certain distance, and then we have to go with the divine imagination, but with all safety systems fully in operation, or the divine imagination will lead us into complete paranoia.",
  "You are not naked when you take off your clothes. You still wear your religious assumptions, your prejudices, your fears, your illusions, your delusions. When you shed the cultural operating system, then, essentially you stand naked before the inspection of your own psyche…and it’s from that position, a position outside the cultural operating system, that we can begin to ask real questions about what does it mean to be human, what kind of circumstance are we caught in, and what kind of structures, if any, can we put in place to assuage the plan and accentuate the glory and the wonder that lurks, waiting for us, in this very narrow slice of time between the birth canal and the yawning grave. In other words we have to return to first premises.",
  "I believe that the use of hallucinogenic mushrooms on the grasslands of Africa gave us the model for all religions to follow. And when, after long centuries of slow forgetting, migration, and climatic change, the knowledge of the mystery was finally lost, we in our anguish traded partnership for dominance, traded harmony with nature for rape of nature, traded poetry for the sophistry of science. In short, we traded our birthright as partners in the drama of the living mind of the planet for the broken pot shards of history, warfare, neurosis, and-if we do not quickly awaken to our predicament-planetary catastrophe.",
  "I think of going to the Grave without having a Psychedelic Experience is like going to the Grave without ever having Sex. It means that you never Figured out what it is all about. The Mystery is in the Body and the way the Body Works itself into Nature.",
  "Feminism is a tremendously underestimated force, viewed in the present context primarily as a woman's concern. The understanding has not yet percolated throughout society that the advancement of women is a program vitally connected to the survival of human beings as a species. The reason for this is simply that institutions take on the character of the atoms which compose them, and what we are most menaced by in the twentieth century are dehumanized institutions. If women played a major role in policy formation and execution on the part of these institutions, I think they would have a far more benign and ecologically sensitive kind of character. So I see feminism not as a kind of war between the sexes or any of these stereotypic images, but as actually a kind of effort to shift the ratios of our emphasis that is expressed through our institutions.",
  "Meaning lies in the confrontation of contradiction - the coincidencia apositorum. That’s what we really feel, not these rational schemes that are constantly beating us over the head with the “thou shalts” and “thou should”, but rather a recovery of the real ambiguity of being and an ability to see ourselves as at once powerful and weak, noble and ignoble, future-oriented, past-facing.",
  "Human beings are co-partners with deity in the project of being. This is the basis of all magic.",
  "If the ego is not regularly and repeatedly dissolved in the unbounded hyperspace of the Transcendent Other, there will always be slow drift away from the sense of self as part of nature’s larger whole. The ultimate consequence of this drift is the fatal ennui that now permeates Western Civilization.",
  "The monkey body has carried us to this moment of release, but we are coming more and more to exist in a world made by the human imagination.",
  "Like the octopi, our destiny is to become what we think, to have our thoughts become our bodies and our bodies become our thoughts. This is the essence of the more perfect Logos envisioned by the Hellenistic polymath Philo Judaeus—a Logos, an indwelling of the Goddess, not heard but beheld. Hans Jonas explains Philo Judaeus's concept as follows: A more perfect archetypal logos, exempt from the human duality of sign and thing, and therefore not bound by the forms of speech, would not require the mediation of hearing, but is immediately beheld by the mind as the truth of things.",
  "From one point of view the Transcendent Other is nature correctly perceived to be alive and intelligent. From another it is the awesomely unfamiliar union of all the senses with memory of the past and anticipation of the future. The Transcendent Other is what one encounters on powerful hallucinogens. It is the crucible of the Mystery of our being, both as a species and as individuals. The Transcendent Other is Nature without her cheerfully reassuring mask of ordinary space, time, and causality.",
  "Monotheism strenuously denies the need to return to a cultural style that periodically places the ego and its values in perspective through contact with a boundary-dissolving immersion in the Archaic mystery of plant-induced, hence mother-associated, psychedelic ecstasy and wholeness, what Joyce called the 'mama matrix most mysterious.'",
  "Neither Bwitists nor Fang felt they could eradicate ritual sin or evil in the world. This incapacity means that men have to celebrate. Good and bad walk together. As Fang frequently enough told missionaries, 'We have two hearts, good and bad'. Early missionaries, aware of these self-confessed contradictions, evangelized with the promise of 'one heartedness' in Christianity. But Fang by and large did not find it there. For many, Christian one heartedness was a constriction of their selves. While 'one heartedness' is celebrated in Bwiti, it is a one heartedness which is coagulated out of a flow of many qualities from one state to another. It is goodness achieved in the presence of badness, an aboveness achieved in the presence of belowness. It is an emergent quality energized in the presence of its opposite.",
  "We are asked by science to believe that the entire universe sprang from nothingness, and at a single point and for no discernible reason. This notion is the limit case for credulity. In other words, if you can believe this, you can believe anything.",
  "The Archaic Revival is a clarion call to recover our birthright, however uncomfortable that may make us. It is a call to realize that life lived in the absence of the psychedelic experience upon which primordial shamanism is based is life trivialized, life denied, life enslaved to the ego and its fear of dissolution in the mysterious matrix of feeling that is all around us. It is in the Archaic Revival that our transcendence of the historical dilemma actually lies.",
  "Reclaim your mind and get it out of the hands of the cultural engineers who want to turn you into a half-baked moron consuming all this trash that's being manufactured out of the bones of a dying world.",
  "The spiritual atrophying of contemporary culture may be due in large measure to its loss of sensitivity to processes in the collective unconscious.",
  "Schizophrenia is just a catch-all term for forms of mental behaviour that we don’t understand. In the nineteenth century there was a term, melancholia, which we would now call bipolar depression… but all forms of sadness, unhappiness, maladaptation, were poured into this label melancholia… Now, schizophrenia is a similar thing… A book about schizophrenia [says that] the typical schizophrenic lives in a world of twilight imagining. Marginal to his society, incapable of holding a regular job, these people live on the fringes content to drift in their own self-created value system. I said, that’s it! That’s it! Now I understand!",
  "It is of the first order of importance to remember this, that the shaman is more than merely a sick man, or a madman; he is a sick man who has healed himself, who is cured, and who must shamanize in order to remain cured.",
  "Things are pretty strange in this world and people do it many ways and you are just an atom in a galaxy of possibilities and your opinions and your science and ‘What I think’ and all that, is just so much noise in a very complex and busy world. And its that same humbling perception that comes out of psychedelics. It just shows you, you’re very parochial.",
  "From a historical point of view, restricting the availability of addictive substances must be seen as a peculiarly perverse example of Calvinist dominator thought - a system in which the sinner is to be punished in this world by being transformed into an exploitable, of his cash, by the criminal/governmental combine that provides the addicitve substances. The image is more horrifying than that of the serpent that devours itself - it is once again the Dionysian image of the mother who devours her children, the image of a house divided against itself.",
  "The war on drugs was never meant to be won. Instead, it will be prolonged as long as possible in order to allow various intelligence operations to wring the last few hundreds of millions of dollars in illicit profits from the global drug scam; then defeat will have to be declared. 'Defeat' will mean, as it did in the case of the Vietnam War, that the media will correctly portray the true dimensions of the situation and the real players, and that public revulsion at the culpability, stupidity and venality of the Establishment's role will force a policy review.",
  "The ultimate singularity is the Big Bang, which physicists believe was responsible for the birth of the universe. We are asked by science to believe that the entire universe sprang from nothingness, at a single point and for no discernible reason. This notion is the limit case for credulity. In other words, if you can believe this, you can believe anything. It is a notion that is, in fact, utterly absurd, yet terribly important. Those so-called rational assumptions flow from this initial impossible situation. Western religion has its own singularity in the form of the apocalypse, an event placed not at the beginning of the universe but at its end. This seems a more logical position than that of science. If singularities exist at all it seems easier to suppose that they might arise out of an ancient and highly complexified cosmos, such as our own, than out of a featureless and dimensionless mega-void",
  "There is no question that a society that sets out to control its citizens' use of drugs sets out on the slippery path to totalitarianism.",
  "The reason we feel alienated is because the society is infantile, trivial, and stupid. So the cost of sanity in this society is a certain level of alienation. I grapple with this because I’m a parent. And I think anybody who has children, you come to this realization, you know—what’ll it be? Alienated, cynical intellectual? Or slack-jawed, half-wit consumer of the horseshit being handed down from on high? There is not much choice in there, you see. And we all want our children to be well adjusted; unfortunately, there’s nothing to be well adjusted to!",
  "No other drug can compete with cannabis for its ability to satisfy the innate yearnings for Archaic boundary dissolution and yet leave intact the structures of ordinary society. If every alcoholic were a pothead, if every crack user were a pothead, if every smoker smoked only cannabis, the social consequences of the ‘drug problem’ would be transformed. Yet, as a society we are not ready to discuss the possibility of self-managed addictions and the possibility of intelligently choosing the plants we ally ourselves to. In time, and perhaps out of desperation, this will come.",
  "The questions of God – meaning in Milton’s phrase “The god who hung the stars like lamps in heaven” – I don’t think psychedelics can address that definitively, but there is another god, a goddess, the goddess of biology, the goddess of the coherent animal human world, the world of the oceans, the atmosphere, and the planet. In short, our world! The world that we were born into, that we evolved into, and that we came from. That world, the psychedelics want to connect us up to… Our individuality, as people and as a species, is an illusion of bad language that the psychedelics dissolve into the greater feeling of connectedness that underlies our being here, and to my mind that’s the religious impulse. It’s not a laundry list of moral dos and don’ts, or a set of dietary prescriptions or practices: it’s a sense of connectedness, responsibility for our fellow human beings and for the earth you walking around on, and because these psychedelics come out of that plant vegetable matrix they are the way back into it.",
  "It was warm and salty, chalky and bittersweet. It tasted like the blood of some old, old thing. I tried not to think about how much at the mercy of these strange people I now was. But in fact my courage was failing. Both Dona Catalina and the guide's mocking eyes had slowly gone cold and mantislike. A wave of insect sound sweeping up the river seemed to splatter the darkness with shards of sharpedged light. I felt my lips go numb. Trying not to appear as loaded as I felt, I crossed to my hammock and lay back. Behind my closed eyelids there was a flowing river of magenta light. It occurred to me in a kind of dream mental pirouette that a helicopter must be landing on top of the hut, and this was the last impression I had. When I regained consciousness I appeared to myself to be surfing on the inner curl of a wave of brightly lit transparent information several hundred feet high. Exhilaration gave way to terror as I realised that my wave was speeding toward a rocky coastline.",
  "I think there's a very strong Calvinistic bias against a free lunch. The idea that you could achieve a spiritual insight without suffering, soul-searching, flagellation, and that sort of thing, is abhorrent to people because they believe that the vision of these higher dimensions should be vouchsafed to the good, and probably to them only after death. It is alarming to people to think that they could take a substance like psilocybin or DMT and have these kinds of experiences.",
  "A hallucination is to be in the presence of that which previously could not be imagined, and if it previously could not be imagined then there is no grounds for believing that you generated it out of yourself.",
  "It’s very important that people take back their minds and that people analyse our dilemma in the context of the entire human story from the descent onto the grassland to our potential destiny as citizens of the galaxy and the universe. We are at a critical turning point and, as I say; the tools, the data that holds the potential for our salvation is now known, it is available: it is among us, but it is misrepresented, it is slandered, it is litigated against, and it’s up to each one of us to relate to this situation in a fashion that will allow us to answer the question that will surely be put to us at some point in the future, which is: What did you do to help save the world?",
  "Every culture that’s ever existed has operated under the illusion that it understood 95% of reality and that the other 5% would be delivered in the next 18 months, and from Egypt forward they’ve been running around believing they had a perfect grip on things and yet we look back at every society that preceded us with great smugness at how naive they all were. Well, it never occurs to us, then, that maybe we’re whistling in the dark too! That the universe is stranger than you CAN suppose, and that that openness that that perception imparts is a great joy, a great blessing, because then you can live your life not in service to some fascistic metaphor but in service to the living mystery: the fact that you’re not going to understand it; it is not going to yield to logic; or magic; or any other technique that’s been developed…",
  "When we look within ourselves with psilocybin, we discover that we do not have to look outward toward the futile promise of life that circles distant stars in order to still our cosmic loneliness. We should look within; the paths of the heart lead to nearby universes full of life and affection for humanity.",
  "What is important is to understand the true boundaries of reality, not the probable boundaries of possible future events. Although boundary conditions operate on the future, they are probabilistic constraints, not absolutely determined fact. We assume that ten minutes hence, the room we are in will still exist. It is a boundary condition that will define the next ten minutes in our space/time coordinate. But we cannot know who will be in the room ten minutes hence; that is free to be determined. One may ask if we can really know that the room will exist at any future moment. This is where induction enters the picture, since in truth we cannot know with certainty. There is no absolutely rigorous way of establishing that. But we can make the inductive leap of faith that has to do with accumulated experience. We project that the existence of the room will remain a boundary condition, but in principle in the next ten minutes there could be an earthquake and this building might not be left standing. However, for that to happen, the boundary condition will have to be radically disrupted in some unexpected and improbable manner. What is so curious is that such a thing could occur.",
  "The cost of sanity in this society, is a certain level﻿ of alienation",
  "Western civilization is a loaded gun pointed at the head of this planet.",
  "If you don't have a plan, you become part of somebody else's plan.",
  "Only psychos and shamans create their own reality",
  "Half the time you think your thinking you’re actually listening",
  "There is a transcendental dimension beyond language... It's just hard as hell to talk about!",
  "The problem is not to find the answer, it's to face the answer",
  "You see, a secret is not something untold. It’s something which can’t be told.",
  "Time will perfect matter.",
  "The bigger you build the bonfire, the more darkness is revealed.",
  "No one knows enough to worry.",
  "Ideology always paves the way toward atrocity.",
  "Human history is a Gaian dream.",
  "You don't want to become so open minded that the wind whistles between your ears.",
  "We live in condensations of our imagination",
  "It’s pretty simple, the ethical life. It’s just demanding.",
  "We are the inheritors of a million years of striving for the unspeakable.",
  "The race isn't to the swift, it's to the thoughtful.",
  "There's only the integrity of doing and having done.",
  "Nowhere is it writ that anthropoid apes should understand reality.",
  "Nature is not mute; it is man who is deaf.",
  "The real truth, that dare not speak itself, is that no one is in control. Absolutely no one.",
  "There is no mundane dimension really, if you have the eyes to see it, it is all transcendental.",
  "Authority will lead you into ruin.",
  "If you cross an onion with a UFO, what you get is a flying saucer that brings tears to your eyes.",
  "You don’t go on bended-knee to petition the official culture for your rights. You have to take them."
]

# create a word and sentence list
sentences = []
words = []

raw_text.each do |quote|
  tmp_words = quote.split(' ')
  tmp_sentences = quote.split(/\./)
  sentences += tmp_sentences
  words += tmp_words
end

# delete sentences consisting of only interpunction
sentences.reject! do |sentence|
  sentence.length < 5
end

# remove whitespace from sentences
sentences.each do |sentence|
  sentence.strip!  
end

# remove uninteresting and confusing words
words.reject! do |word|
 %w(and a an - the it).include? word
end

# format words by removing interpunction
words.each do |word| 
  word.gsub!(/[\.\'\,\?\!]/, '')
  word.downcase!
end

sentences.each do |sentence|
  Sentence.create(text: sentence)
end

words.each do |word|
  Word.create(text: word)
end

puts "Created #{Word.count} words!"
puts "Created #{Sentence.count} sentences!"

# # create a paragraph
# num = rand(3) + 2 # take 2-4 sentences
# paragraph_sentences = sentences.sample(num)

# # randomly change 20% of the words to make it more lorem ipsum like
# paragraph_sentences.map! do |sentence|
#   sentence.split(' ').map! {|word| rand < 0.15 ? words.sample : word}.uniq.join(' ').capitalize << '.'
# end

# puts paragraph_sentences.join(' ')





